### ISSUE TITLE
Pyvista version

### ISSUE THREAD

**Issue by burningsage** [emerald-geomodelling/EmeraldTriangles#14]
There appear to be a depencency issues on Pyvista version. 
pyvista==0.36.1 is tested and works fine, but it does have this warning: 
```
/Users/bbloss/EMeraldCodes/VirtualEnvironments/EMerald_Interpret_gui_master_20230207/lib/python3.9/site-packages/pyvista/core/dataset.py:1458: PyvistaDeprecationWarning: Use of `point_arrays` is deprecated. Use `point_data` instead.
  warnings.warn(
/Users/bbloss/EMeraldCodes/VirtualEnvironments/EMerald_Interpret_gui_master_20230207/lib/python3.9/site-packages/pyvista/core/dataset.py:1595: PyvistaDeprecationWarning: Use of `cell_arrays` is deprecated. Use `cell_data` instead.
  warnings.warn(
```

pyvista==0.38.1 breaks with a note about needing point_data (I've downgraded my pyvista to make it work, so I don't have the specific traceback for this version...)

**Comment by eddjharrison** [comment]
Yeah I recognise this, what were you generating for it to fall over ben? fairly easy fix, just need some time to implement it across our export routines using pyvista
